<?xml version="1.0"?>
<package format="3">
  <name>franzi_description</name>
  <version>0.1.0</version>
  <description>URDF, meshes, and joint-name configuration for the Franzi humanoid robot.</description>

  <maintainer email="jiang.hanchong@fmc3-robotics.ai">Hanchong Jiang</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <architecture_independent/>
  </export>
</package>
